#!/usr/bin/env bash
## Description: Run Rector
## Usage: rector [rector-args]
set -euo pipefail
[[ -x vendor/bin/rector ]] || { echo 'Error: rector is not installed.' >&2; exit 1; }
php vendor/bin/rector "$@"
