#!/usr/bin/env bash
## Description: Run PHPStan
## Usage: stan [phpstan-args]
set -euo pipefail
[[ -x vendor/bin/phpstan ]] || { echo 'Error: phpstan is not installed.' >&2; exit 1; }
php vendor/bin/phpstan "$@"
