name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Environment setup
        uses: ddev/github-action-setup-ddev@v1
        with:
          ddev-version: ${{ matrix.ddev_version }}

      - name: Bats test
        run: bats ./tests/test.bats
